class1 = input("Enter the number of students in class 1: ")
group1 = input("Enter the number of groups to form in class 1: ")
class2 = input("Enter the number of students in class 2: ")
group2 = input("Enter the number of groups to form in class 2: ")
class3 = input("Enter the number of students in class 3: ")
group3 = input("Enter the number of groups to form in class 3: ")
print("Number of students in each group:")
print("Class 1: " + str(int(class1)//int(group1)))
print("Class 2: " + str(int(class2)//int(group2)))
print("Class 3: " + str(int(class3)//int(group3)))
print("Number of students leftover:")
print("Class 1: " + str(int(class1)%int(group1)))
print("Class 2: " + str(int(class2)%int(group2)))
print("Class 3: " + str(int(class3)%int(group3)))
